### ISSUE TITLE
[FS Chat] Enter button doesn't send message

### ISSUE THREAD

**Issue by TemporaryCrown** [FrankerFaceZ/Add-Ons#218] opened 2024-05-13 04:19 UTC
Enter button doesn't work to send a message it just brakes the chat box text on edge and chrome.

https://github.com/FrankerFaceZ/Add-Ons/assets/77809605/4b68b2d5-78ae-47e2-8aa3-3155302cdccc

**Comment by Tai-Mai** [comment] 2024-05-16 05:54
This is a duplicate of #217

**Comment by TemporaryCrown** [comment] 2024-05-20 01:17
Its only for the Fullscreen video chat not the twitch chat text box. The original chat text box works fine when pressing enter

**Comment by Tai-Mai** [comment] 2024-05-20 05:19
Yes, this has also already been commented before. https://github.com/FrankerFaceZ/Add-Ons/issues/217#issuecomment-2105957587

**Comment by RYJASM** [comment] 2024-05-31 10:36
> Yes, this has also already been commented before. [#217 (comment)](https://github.com/FrankerFaceZ/Add-Ons/issues/217#issuecomment-2105957587)

It's till an issue.

**Comment by spxplucky** [comment] 2024-06-04 14:04
I have the same problem.

**Comment by SirStendec** [comment] 2024-10-22 20:35
Duplicate of #217

**Closed by SirStendec** 2024-10-22 20:35 UTC
Labels: duplicate
