### ISSUE TITLE
Fullscreen Chat: Chat identity button broken

### ISSUE THREAD

**Issue by RYJASM** [FrankerFaceZ/Add-Ons#222] opened 2024-05-31 10:44 UTC
Clicking the chat identity button in the full screen chat overlay next to the input field doesn't do anything. The expected result would be that the chat identity settings would slide up at the bottom of the chat area.

**Comment by SirStendec** [comment] 2024-10-22 20:35
Duplicate of #217

**Closed by SirStendec** 2024-10-22 20:35 UTC
Labels: duplicate
