### ISSUE TITLE
Fullscreen Chat: Chat Paused Due to Scroll overlay button doesn't work

### ISSUE THREAD

**Issue by RYJASM** [FrankerFaceZ/Add-Ons#225] opened 2024-05-31 10:54 UTC
Repeatable issue: open fullscreen chat overlay, scroll up in the chat messages until the "Chat Paused Due to Scroll" button appears over the bottom of the chat. Click the button. Nothing happens.

Expected result: Clicking the "Chat Paused Due to Scroll" button should reset the position of the scroll to the bottom so the newest messages are shown and the button fades away.

**Comment by SirStendec** [comment] 2024-10-22 20:35
Duplicate of #217

**Closed by SirStendec** 2024-10-22 20:35 UTC
Labels: duplicate
